### ISSUE TITLE
Setup Wazuh on All Servers

### ISSUE THREAD

**Issue by kralouf** [cweb-cybr/ApplicationSecurityTeam#2]
Setting up Wazuh on ALL servers for security analysis

IP: 172.234.219.130

**Comment by kralouf** [comment]
Wazuh has been connected to Jenkins

**Comment by kralouf** [comment]
Wazuh has been connected to SonarQube

**Comment by akawilk** [comment]
Wazuh agent setup and running on SonarQube sever. - Completed
Wazuh agent setup and running on Jenkins server. - Completed
Wazuh agent setup and running on Appserver. - Completed

**Comment by kralouf** [comment]
Wazuh agent setup and running on Wazuh server. - Completed

**Comment by kralouf** [comment]
Confirmed all servers has Wazuh on it.
