### ISSUE TITLE
Jenkins Pipeline Configuration

### ISSUE THREAD

**Issue by kralouf** [cweb-cybr/ApplicationSecurityTeam#4]
**Jenkins Pipeline Requirements:**

- Automate connections between GitHub, Jenkins, SonarQube Scanner, Application Server/Application itself, and DockerHub.
- Pipeline MUST Include:
  - Code Vulnerability Scans (Static/Dynamic)
  - Code Duplication Checks
  - Code Smell Detection
  - Code Standard Compliance Checks
  - Security and Vulnerability Analysis (via SonarQube and Snyk)

Wait until Jenkins Server has been created

**Comment by jackpendergast** [comment]
Waiting for credentials from Khremin

**Comment by kralouf** [comment]
verified pipeline works, jack fixed it, gold star
