### ISSUE TITLE
Securing API Configurations and Credentials (avoiding plaintext)

### ISSUE THREAD

**Issue by kralouf** [cweb-cybr/ApplicationSecurityTeam#5]
This will be in Jenkins, Github, and Snyk. All 3 use API Keys.
Secure the Jenkins Pipeline (once created) to avoid plaintext credentials

**Comment by mankhec** [comment]
Added Jenkin Credentials for Snyk, Dockerhub, SonarQube

**Comment by kralouf** [comment]
Re-add credentials

**Comment by mankhec** [comment]
Re-added credentials. Max broke the jenkins server.

**Comment by kralouf** [comment]
Verified credentials were re-added, khemrin broke it

**Comment by kralouf** [comment]
khemrin broke it

**Comment by kralouf** [comment]
Had issues with original API token based on using my personal account, I ended up re-adding my Snyk api token, and worked integrating between jenkins, github, and snyk

**Comment by kralouf** [comment]
is true, khemrin added a space for dockerhub creds, man
