### ISSUE TITLE
Security Hardening on Servers

### ISSUE THREAD

**Issue by kralouf** [cweb-cybr/ApplicationSecurityTeam#9]
Utilize results from Wazuh to get security score to be **90% and above** on ALL servers.

**Comment by kralouf** [comment]
Useful resource from jason: https://github.com/wazuh/wazuh/issues/13968

Basically, manually fixes it if need be

**Comment by kralouf** [comment]
^^ or determines issues

**Comment by espdun** [comment]
Don't remove iptables on any of the servers as it messes with docker.
